// GENERATED FILE — do not edit by hand.
// Produced by scripts/generate-synonyms.mjs from
// scripts/synonym-sheets/paleoData_variableName.csv.
// Each entry maps an observed raw variableName synonym → its canonical LiPD
// variableName. 1581 entries.

export const VARIABLE_NAME_SYNONYMS: ReadonlyArray<readonly [string, string]> = [
  ["#ofSites", "siteCount"],
  ["% Ca-detr", "calcium"],
  ["% Ca-ex", "calcium"],
  ["% CaCO3-ex", "CaCO3"],
  ["% Carbonate", "carbonate"],
  ["% Dolomite", "dolomite"],
  ["% IC", "TIC"],
  ["% K", "potassium"],
  ["% Mg", "magnesium"],
  ["% Mn", "manganese"],
  ["% OC", "organicCarbon"],
  ["% Organic carbon", "organicCarbon"],
  ["% TC", "carbon"],
  ["% Ti", "titanium"],
  ["% Total C", "carbon"],
  ["%_clay", "clay"],
  ["%_lithics", "lithics"],
  ["%_sand", "sand"],
  ["%_silt", "silt"],
  ["%_tc", "carbon"],
  ["%_tom", "organicMatter"],
  ["%benth.dia", "diatom"],
  ["%Benthic", "diatom"],
  ["%fresh", "diatom"],
  ["%Indif.", "diatom"],
  ["%K", "potassium"],
  ["%Mg", "magnesium"],
  ["%O", "oxygen"],
  ["%P", "phosphorus"],
  ["%plank.dia", "diatom"],
  ["%Saline", "diatom"],
  ["%saline.dia", "diatom"],
  ["%Ti", "titanium"],
  ["∆RH_lower", "uncertaintyLow"],
  ["∆RH_mid", "deltaRelativeHumidity"],
  ["∆RH_upper", "uncertaintyHigh"],
  ["∑LREE/∑HREE", "epsilonLREE/epsilonHREE"],
  ["∑REE", "epsilonREE"],
  ["<16 μm", "grainSize"],
  ["<2 um", "grainSize"],
  ["<2um", "grainSize"],
  ["<4 um", "grainSize"],
  [">63 um", "grainSize"],
  ["0.025_quantile_dust_flux", "uncertaintyLow95"],
  ["0.25_quantile_dust_flux", "uncertaintyHigh50"],
  ["0.50_quantile_dust_flux", "dust"],
  ["0.75_quantile_dust_flux", "uncertaintyHigh50"],
  ["0.975_quantile_dust_flux", "uncertaintyHigh95"],
  ["13CleafwaxC29-33err", "uncertainty"],
  ["2 sigma", "uncertainty2s"],
  ["250-31 um", "grainSize"],
  ["2H_dino_1sig", "uncertainty1s"],
  ["63-4 um", "grainSize"],
  ["95LowerAge", "uncertaintyLow95"],
  ["95UpperAge", "uncertaintyHigh95"],
  ["A", "deleteThisColumn"],
  ["A_site_std", "uncertainty"],
  ["A/C", "pollenRatio"],
  ["A/C Ratio", "pollenRatio"],
  ["abundance", "count"],
  ["acc", "accumulation"],
  ["Acc max", "uncertaintyHigh"],
  ["Acc min", "uncertaintyLow"],
  ["Acc Rate TOC", "organicCarbon"],
  ["Accumulation", "accumulation"],
  ["Accumulation rate ice (kg/m2/yr)", "accumulation"],
  ["ACL (27-33)", "ACL"],
  ["ACL25-35", "ACL"],
  ["ACL27-31", "ACL"],
  ["ACLC22-30", "ACL"],
  ["Adjusted Depth", "depth"],
  ["Age", "age"],
  ["age max", "uncertaintyHigh"],
  ["age min", "uncertaintyLow"],
  ["age_2.5", "uncertaintyLow95"],
  ["age_5thpercentile", "uncertaintyLow90"],
  ["age_95thpercentile", "uncertaintyLow90"],
  ["age_97.5", "uncertaintyHigh95"],
  ["age_alt", "age"],
  ["age_calBP95-", "uncertaintyLow95"],
  ["age_calBP95+", "uncertaintyHigh95"],
  ["age_Calibrated", "age"],
  ["age_CE", "year"],
  ["Age_kaBP_2.5percentile", "uncertaintyLow95"],
  ["Age_kaBP_97.5percentile", "uncertaintyHigh95"],
  ["age_max", "uncertaintyHigh"],
  ["age_min", "uncertaintyLow"],
  ["age_old", "uncertaintyHigh"],
  ["Age_original", "age"],
  ["Age_uncertainty", "uncertainty"],
  ["age_y_bp-1s", "uncertaintyLow1s"],
  ["age_y_bp+1s", "uncertaintyHigh1s"],
  ["age_young", "uncertaintyLow"],
  ["Age, uncertainty (±)", "uncertainty"],
  ["age2.5", "uncertaintyLow95"],
  ["age95ConfMin", "uncertaintyLow95"],
  ["age95conMax", "uncertaintyHigh95"],
  ["age97.5", "uncertaintyLow90"],
  ["ageBacon", "age"],
  ["ageBaconUncertaintyHigh", "uncertaintyHigh"],
  ["ageBaconUncertaintyLow", "uncertaintyLow"],
  ["ageBchron", "age"],
  ["ageBchronUncertaintyHigh", "uncertaintyHigh"],
  ["ageBchronUncertaintyLow", "uncertaintyLow"],
  ["agecopRa", "age"],
  ["agecopRaUncertaintyHigh", "uncertaintyHigh"],
  ["agecopRaUncertaintyLow", "uncertaintyLow"],
  ["ageDuplicate", "age"],
  ["ageEnsemble", "age"],
  ["ageError", "uncertainty"],
  ["agelinInterp", "age"],
  ["agelinInterpUncertaintyHigh", "uncertaintyHigh"],
  ["agelinInterpUncertaintyLow", "uncertaintyLow"],
  ["agelinReg", "age"],
  ["agelinRegUncertaintyHigh", "uncertaintyHigh"],
  ["agelinRegUncertaintyLow", "uncertaintyLow"],
  ["ageMarine09", "age"],
  ["ageMax", "uncertaintyHigh"],
  ["ageMedian", "age"],
  ["ageMedianBacon", "age"],
  ["ageMin", "uncertaintyLow"],
  ["ageOld", "uncertaintyHigh"],
  ["ageOriginal", "age"],
  ["ageOther", "age"],
  ["ageOxCal", "age"],
  ["ageOxCalUncertaintyHigh", "uncertaintyHigh"],
  ["ageOxCalUncertaintyLow", "uncertaintyLow"],
  ["ageRounded", "age"],
  ["ageStalAge", "age"],
  ["ageStalAgeUncertaintyHigh", "uncertaintyHigh"],
  ["ageStalAgeUncertaintyLow", "uncertaintyLow"],
  ["ageUncertainty", "uncertainty"],
  ["ageUncertaintyHigh", "uncertaintyHigh"],
  ["ageUncertaintyLow", "uncertaintyLow"],
  ["ageUncertaintyOther", "uncertainty"],
  ["ageYoung", "uncertaintyLow"],
  ["Al", "aluminum"],
  ["Al peak area", "aluminum"],
  ["AL2O3", "Al2O3"],
  ["AlProp", "aluminum"],
  ["Amps", "amps"],
  ["Annual Precipitation", "precipitation"],
  ["Annual Precipitation Error", "uncertainty"],
  ["APR", "temperature"],
  ["April–August precipitation", "precipitation"],
  ["AprQ", "streamflow"],
  ["Aragonite", "aragonite"],
  ["arm_irm", "ARM/IRM"],
  ["ARS", "ARSTAN"],
  ["As", "arsenic"],
  ["AUG", "temperature"],
  ["AugQ", "streamflow"],
  ["average C26 C28", "deleteThisColumn"],
  ["Average Chain Length", "ACL"],
  ["AverageChainLength20to30", "ACL"],
  ["AverageChainLength20to32", "ACL"],
  ["Avg_MS", "MS"],
  ["AVG_MS_DRS1_2A_3_2B_4", "MS"],
  ["B", "boron"],
  ["Ba", "barium"],
  ["Ba (ppm)", "barium"],
  ["Ba peak area", "barium"],
  ["Ba_Ca", "Ba/Ca"],
  ["BaCa", "Ba/Ca"],
  ["bagd18O", "d18O"],
  ["bagdD", "d2H"],
  ["bagDexcess", "deuteriumExcess"],
  ["basintype", "notes"],
  ["Be", "beryllium"],
  ["benthic.d13C", "d13C"],
  ["benthic.d13C.error", "uncertainty"],
  ["benthic.d18O", "d18O"],
  ["benthic.d18O.error", "uncertainty"],
  ["benthic.MgCa", "Mg/Ca"],
  ["benthic.MgCa.error", "uncertainty"],
  ["BioSi", "BSi"],
  ["BITindex", "BIT"],
  ["BITindex-3pt", "BIT"],
  ["blueIntensity", "reflectance"],
  ["bot", "depthBottom"],
  ["Bottom Depth", "depthBottom"],
  ["bottom depth in section", "depthBottom"],
  ["Bottom_depth", "depthBottom"],
  ["bottomDepth", "depthBottom"],
  ["Br", "bromine"],
  ["br1020", "brGDGT-Ib"],
  ["br1036", "brGDGT-IIa5me"],
  ["br1048", "brGDGT-IIIb5me"],
  ["br1050", "brGDGT-IIIa5me"],
  ["brGDGT", "GDGT"],
  ["brGDGT-IIa", "brGDGT-IIa5me"],
  ["brGDGT-IIa'", "brGDGT-IIa6me"],
  ["brGDGT-IIb", "brGDGT-IIb5me"],
  ["brGDGT-IIb'", "brGDGT-IIb6me"],
  ["brGDGT-IIc", "brGDGT-IIc5me"],
  ["brGDGT-IIc'", "brGDGT-IIc6me"],
  ["brGDGT-IIIa", "brGDGT-IIIa5me"],
  ["brGDGT-IIIa'", "brGDGT-IIIa6me"],
  ["brGDGT-IIIb", "brGDGT-IIIb5me"],
  ["brGDGT-IIIb'", "brGDGT-IIIb6me"],
  ["brGDGT-IIIc", "brGDGT-IIIc5me"],
  ["brGDGT-IIIc'", "brGDGT-IIIc6me"],
  ["brGDGTIa", "brGDGT-Ia"],
  ["brGDGTIb", "brGDGT-Ib"],
  ["brGDGTIia", "brGDGT-IIa5me"],
  ["brGDGTIib", "brGDGT-IIb5me"],
  ["brGDGTIIIa", "brGDGT-IIIa5me"],
  ["brGDGTIIIb", "brGDGT-IIIb5me"],
  ["Brightness", "reflectance"],
  ["Bsi_3pt", "BSi"],
  ["Bsi_Raw", "BSi"],
  ["BSi_regime", "notes"],
  ["bubbleNumberDensityError", "uncertainty"],
  ["bulk density", "bulkDensity"],
  ["Bulk MAR", "MAR"],
  ["Bulk OM d13C", "d13C"],
  ["Bulk OM d15N", "d15N"],
  ["bulkMAR", "MAR"],
  ["C", "carbon"],
  ["C_N", "C/N"],
  ["C_organic_flux", "organicCarbon"],
  ["C/N organic", "C/N"],
  ["C13bulk", "d13C"],
  ["c14age", "age14C"],
  ["C20 concentration", "C20n-alkanoicAcid"],
  ["C20 d2H", "d2H"],
  ["C20 d2H SEM", "d2H"],
  ["C20 FAME Concentration", "C20n-alkanoicAcid"],
  ["C20 n", "C20n-alkanoicAcid"],
  ["C20 SEM", "C20n-alkanoicAcid"],
  ["C20 Total Unc", "uncertainty"],
  ["C20concentration", "C20n-alkanoicAcid"],
  ["C20d2H", "d2H"],
  ["C20FAMEconcentration", "C20n-alkanoicAcid"],
  ["C20n", "C20n-alkanoicAcid"],
  ["C20n-alkenoicAcid", "C20n-alkanoicAcid"],
  ["C20SEM", "C20n-alkanoicAcid"],
  ["C21 concentration", "C21n-alkanoicAcid"],
  ["C21 d13C", "d13C"],
  ["C21 d2H", "d2H"],
  ["C21 FAME Concentration", "C21n-alkanoicAcid"],
  ["C21FAMEconcentration", "C21n-alkanoicAcid"],
  ["C22 d2H", "d2H"],
  ["C22 d2H SEM", "d2H"],
  ["C22 FAME Concentration", "C22n-alkanoicAcid"],
  ["C22 n", "C22n-alkanoicAcid"],
  ["C22 SEM", "C22n-alkanoicAcid"],
  ["C22 Total Unc", "uncertainty"],
  ["C22concentration", "C22n-alkanoicAcid"],
  ["C22d2H", "d2H"],
  ["C22FAMEconcentration", "C22n-alkanoicAcid"],
  ["C22n", "C22n-alkanoicAcid"],
  ["C22SEM", "C22n-alkanoicAcid"],
  ["C23 concentration", "C23n-alkanoicAcid"],
  ["C23 d13C", "d13C"],
  ["C23 d2H", "d2H"],
  ["C23 FAME Concentration", "C23n-alkanoicAcid"],
  ["C23 n", "C23n-alkanoicAcid"],
  ["C23 stdev", "uncertainty1s"],
  ["C23 δD", "d2H"],
  ["C23 δD std dev", "uncertainty1s"],
  ["C23C31", "C23n-alkanoicAcid"],
  ["C23FAMEconcentration", "C23n-alkanoicAcid"],
  ["C24 concentration", "C24n-alkanoicAcid"],
  ["C24 d2H", "d2H"],
  ["C24 d2H stdev", "uncertainty1s"],
  ["C24 FAME Concentration", "C24n-alkanoicAcid"],
  ["C24 n", "C24n-alkanoicAcid"],
  ["C24 SEM", "C24n-alkanoicAcid"],
  ["C24 Total Unc", "uncertainty"],
  ["C24concentration", "C24n-alkanoicAcid"],
  ["C24d2H", "d2H"],
  ["C24FAMEconcentration", "C24n-alkanoicAcid"],
  ["C24n", "C24n-alkanoicAcid"],
  ["C24SEM", "C24n-alkanoicAcid"],
  ["C25 concentration", "C25n-alkanoicAcid"],
  ["C25 d13C", "d13C"],
  ["C25 d2H", "d2H"],
  ["C25 FAME Concentration", "C25n-alkanoicAcid"],
  ["C25 n", "C25n-alkanoicAcid"],
  ["C25 stdev", "uncertainty1s"],
  ["C25 δD", "d2H"],
  ["C25 δD std dev", "uncertainty1s"],
  ["C25:2 concentration", "C25_2n-alkanoicAcid"],
  ["C25:2 d13C", "d13C"],
  ["C25:2 d2H", "d2H"],
  ["C25FAMEconcentration", "C25n-alkanoicAcid"],
  ["C26 concentration", "C26n-alkanoicAcid"],
  ["C26 d2H", "d2H"],
  ["C26 d2H SEM", "d2H"],
  ["C26 FAME Concentration", "C26n-alkanoicAcid"],
  ["C26 n", "C26n-alkanoicAcid"],
  ["C26 SEM", "C26n-alkanoicAcid"],
  ["C26 Total Unc", "uncertainty"],
  ["C26concentration", "C26n-alkanoicAcid"],
  ["C26d2H", "d2H"],
  ["C26FAMEconcentration", "C26n-alkanoicAcid"],
  ["C26n", "C26n-alkanoicAcid"],
  ["C26OH0x2F0x28C26OH0x2BC290x29", "C26n-alkanoicAcid"],
  ["C26SEM", "C26n-alkanoicAcid"],
  ["C27 concentration", "C27n-alkanoicAcid"],
  ["C27 d13C", "d13C"],
  ["C27 d2H", "d2H"],
  ["C27 FAME Concentration", "C27n-alkanoicAcid"],
  ["C27 n", "C27n-alkanoicAcid"],
  ["C27 stdev", "uncertainty1s"],
  ["C27FAMEconcentration", "C27n-alkanoicAcid"],
  ["C28 concentration", "C28n-alkanoicAcid"],
  ["C28 d13C vs. VPDB", "d13C"],
  ["C28 d2H", "d2H"],
  ["C28 d2H SEM", "d2H"],
  ["C28 FAME Concentration", "C28n-alkanoicAcid"],
  ["C28 n", "C28n-alkanoicAcid"],
  ["C28 SEM", "C28n-alkanoicAcid"],
  ["C28 Total Unc", "uncertainty"],
  ["C28_dD", "d2H"],
  ["C28_dDIV", "d2H"],
  ["C28concentration", "C28n-alkanoicAcid"],
  ["C28d2H", "d2H"],
  ["C28FAMEconcentration", "C28n-alkanoicAcid"],
  ["C28n", "C28n-alkanoicAcid"],
  ["C28SEM", "C28n-alkanoicAcid"],
  ["C29 concentration", "C29n-alkanoicAcid"],
  ["C29 d13C", "d13C"],
  ["C29 d13C std dev", "uncertainty1s"],
  ["C29 d2H", "d2H"],
  ["C29 dD", "d2H"],
  ["C29 dD std dev", "uncertainty1s"],
  ["C29 FAME Concentration", "C29n-alkanoicAcid"],
  ["C29 n", "C29n-alkanoicAcid"],
  ["C29 stdev", "uncertainty1s"],
  ["C29 δ13C", "d13C"],
  ["C29 δ13C std dev", "uncertainty1s"],
  ["C29 δ13C std dev [±]", "uncertainty1s"],
  ["C29 δD", "d2H"],
  ["C29 δD Corrected", "d2H"],
  ["C29 δD ice volume adjusted", "d2H"],
  ["C29 δD ice volume and vegetation adjusted", "d2H"],
  ["C29 δD std dev", "uncertainty1s"],
  ["C29 δD std dev [±]", "uncertainty1s"],
  ["C29-C31 δD", "d2H"],
  ["C29FAMEconcentration", "C29n-alkanoicAcid"],
  ["C30 concentration", "C30n-alkanoicAcid"],
  ["C30 d2H", "d2H"],
  ["C30 d2H SEM", "d2H"],
  ["C30 dD", "d2H"],
  ["C30 dD IV corrected  (3°C)", "d2H"],
  ["C30 dD IV corrected  (7°C)", "d2H"],
  ["C30 dD std dev", "uncertainty1s"],
  ["C30 FAME Concentration", "C30n-alkanoicAcid"],
  ["C30 n", "C30n-alkanoicAcid"],
  ["C30 SEM", "C30n-alkanoicAcid"],
  ["C30 Total Unc", "uncertainty"],
  ["C30concentration", "C30n-alkanoicAcid"],
  ["C30d2H", "d2H"],
  ["C30FAMEconcentration", "C30n-alkanoicAcid"],
  ["C30n", "C30n-alkanoicAcid"],
  ["C30SEM", "C30n-alkanoicAcid"],
  ["C31 concentration", "C31n-alkanoicAcid"],
  ["C31 d13C", "d13C"],
  ["C31 d13C std dev", "uncertainty1s"],
  ["C31 d2H", "d2H"],
  ["C31 dD", "d2H"],
  ["C31 dD std dev", "uncertainty1s"],
  ["C31 δ13C", "d13C"],
  ["C31 δ13C std dev", "uncertainty1s"],
  ["C31 δD", "d2H"],
  ["C31 δD std dev", "uncertainty1s"],
  ["C31d13C_PDB", "d13C"],
  ["C31d13Csd", "uncertainty1s"],
  ["C31dD", "d2H"],
  ["C31dDsd", "d2H"],
  ["C31FAMEconcentration", "C31n-alkanoicAcid"],
  ["C32 dD", "d2H"],
  ["C32FAMEconcentration", "C31n-alkanoicAcid"],
  ["C33 δ13C", "d13C"],
  ["C33 δ13C Std Dev", "uncertainty1s"],
  ["C33 δD", "d2H"],
  ["C33 δD Std Dev", "uncertainty1s"],
  ["C34:4", "C37:4Alkenone"],
  ["C37:2", "C37:2Alkenone"],
  ["C37:3a", "C37:3aAlkenone"],
  ["C37:3b", "C37:3bAlkenone"],
  ["C37.concentration", "C37Alkenone"],
  ["C370x3A4", "C37:4Alkenone"],
  ["Ca", "calcium"],
  ["Ca  peak area", "calcium"],
  ["Ca__", "calcium"],
  ["Ca/Ti-z", "Ca/Ti"],
  ["caaxis1", "CCA1"],
  ["caaxis2", "CCA2"],
  ["CaCO3-IC", "CaCO3"],
  ["CAL", "deleteThisColumn"],
  ["cal_age_range_old", "uncertaintyHigh"],
  ["cal_age_range_young", "uncertaintyLow"],
  ["calcification", "calcificationRate"],
  ["Calcite", "calcite"],
  ["Calibrated", "deleteThisColumn"],
  ["Calibration Error", "uncertainty"],
  ["CaProp", "calcium"],
  ["carb%", "carbonate"],
  ["CarbonPreferenceIndex20to30", "CPI"],
  ["CarbonPreferenceIndex20to32", "CPI"],
  ["CBTsd", "uncertainty1s"],
  ["Cd", "cadmium"],
  ["Cd MAR (ug/cm2/ky)", "cadmium"],
  ["CDR3_d13C", "d13C"],
  ["CDR3_d18O", "d18O"],
  ["CDR3_MgCa", "Mg/Ca"],
  ["CDR3_SrCa", "Sr/Ca"],
  ["chacoal_influx", "charcoal"],
  ["chemical index of alteration", "CIA"],
  ["Chironomid d18O", "d18O"],
  ["Chironomid d18O max", "uncertaintyHigh"],
  ["Chironomid d18O min", "uncertaintyLow"],
  ["Cl", "chlorine"],
  ["Cl_", "chlorine"],
  ["clastic", "sedimentDry"],
  ["clastic_flux", "sedimentDry"],
  ["Clay", "clay"],
  ["cluster2", "cluster"],
  ["Co", "cobalt"],
  ["CodeName", "notes"],
  ["color", "notes"],
  ["CommentRegardingReliability", "notes"],
  ["Commentregardingreliability1", "notes"],
  ["Commentregardingreliability2", "notes"],
  ["Commentregardingreliability3", "notes"],
  ["Commentregardingreliability4", "notes"],
  ["Composite depth", "depth"],
  ["Composite depth bottom", "depthBottom"],
  ["Composite Depth in Core", "depth"],
  ["Composite depth mid", "depth"],
  ["Composite depth top", "depthTop"],
  ["Composite_depth", "depth"],
  ["compositeDepth", "depth"],
  ["Concentration (C25-35)", "concentration"],
  ["cor_depth_cm", "depth"],
  ["CordMAR", "MAR"],
  ["Core", "core"],
  ["Core depth", "depth"],
  ["Core ID", "core"],
  ["core name", "core"],
  ["Core Section", "core"],
  ["Core_number", "core"],
  ["core_section", "section"],
  ["CoreName", "core"],
  ["CoreSect1H", "core"],
  ["CoreSite", "site"],
  ["Corg", "organicCarbon"],
  ["Corg dens", "organicCarbon"],
  ["corrs", "correlationCoefficient"],
  ["count_analyses_B3", "count"],
  ["count_analyses_C2", "count"],
  ["count_analyses_C3", "count"],
  ["count_analyses_C5", "count"],
  ["count_analyses_C6", "count"],
  ["CPI (27-33)", "CPI"],
  ["CPI_25-33", "CPI"],
  ["CPI22-30", "CPI"],
  ["Cr", "chromium"],
  ["cren'", "Cren'"],
  ["Cren/cren'", "Cren/Cren'"],
  ["Cu", "copper"],
  ["d excess stdev", "uncertainty1s"],
  ["d-excess", "deuteriumExcess"],
  ["d-excess pore ice", "deuteriumExcess"],
  ["d-excess pore ice sw corr", "deuteriumExcess"],
  ["d-excess sw", "deuteriumExcess"],
  ["d-excess_swcorr", "deuteriumExcess"],
  ["d13/12C", "d13C"],
  ["D13C", "d13C"],
  ["d13C bulk", "d13C"],
  ["d13C bulk calcite", "d13C"],
  ["d13C C18 FAME", "d13C"],
  ["d13C C18 FAME SEM", "d13C"],
  ["d13C C20 FAME", "d13C"],
  ["d13C C20 FAME SEM", "d13C"],
  ["d13C C21 alkane", "d13C"],
  ["d13C C21 alkane SEM", "d13C"],
  ["d13C C22 FAME", "d13C"],
  ["d13C C22 FAME SEM", "d13C"],
  ["d13C C23 alkane", "d13C"],
  ["d13C C23 alkane SEM", "d13C"],
  ["d13C C24 FAME", "d13C"],
  ["d13C C24 FAME SEM", "d13C"],
  ["d13C C25", "d13C"],
  ["d13C C25 alkane", "d13C"],
  ["d13C C25 alkane SEM", "d13C"],
  ["d13C C26 FAME", "d13C"],
  ["d13C C26 FAME SEM", "d13C"],
  ["d13C C27", "d13C"],
  ["d13C C27 alkane", "d13C"],
  ["d13C C27 alkane SEM", "d13C"],
  ["d13C C28 FAME", "d13C"],
  ["d13C C28 FAME SEM", "d13C"],
  ["d13C C29", "d13C"],
  ["d13C C29 alkane", "d13C"],
  ["d13C C29 alkane SEM", "d13C"],
  ["d13C C30 FAME", "d13C"],
  ["d13C C30 FAME SEM", "d13C"],
  ["d13C C31", "d13C"],
  ["d13C C31 alkane", "d13C"],
  ["d13C C31 alkane SEM", "d13C"],
  ["d13C C32 FAME", "d13C"],
  ["d13C C32 FAME SEM", "d13C"],
  ["d13C C33 alkane", "d13C"],
  ["d13C C33 alkane SEM", "d13C"],
  ["d13C C34 FAME", "d13C"],
  ["d13C C34 FAME SEM", "d13C"],
  ["d13C C35 alkane", "d13C"],
  ["d13C C35 alkane SEM", "d13C"],
  ["d13C carbonate", "d13C"],
  ["d13C Error", "uncertainty"],
  ["d13C organic", "d13C"],
  ["d13C ostracod", "d13C"],
  ["d13C std dev", "uncertainty"],
  ["d13C VPDB", "d13C"],
  ["d13C_2.5", "uncertaintyLow95"],
  ["d13C_97.5", "uncertaintyHigh95"],
  ["d13c_bulloides", "d13C"],
  ["D13C_C28", "d13C"],
  ["D13C_C30", "d13C"],
  ["d13C_C31", "d13C"],
  ["d13C_C31_sd", "uncertainty1s"],
  ["d13c_dutertrei", "d13C"],
  ["d13C_error", "uncertainty"],
  ["D13C_FAME", "d13C"],
  ["d13C_org", "d13C"],
  ["d13c_pachyderma", "d13C"],
  ["d13c_pachyderma_d", "d13C"],
  ["d13c_ruber", "d13C"],
  ["d13c_ruber_pink", "d13C"],
  ["d13c_sacculifer", "d13C"],
  ["D13C-", "uncertaintyLow"],
  ["D13C+", "uncertaintyHigh"],
  ["d13Ccarb", "d13C"],
  ["d13CComposite", "d13C"],
  ["d13CleafwaxC27", "d13C"],
  ["d13CleafwaxC27err", "d13C"],
  ["d13CleafwaxC29", "d13C"],
  ["d13CleafwaxC29err", "d13C"],
  ["d13CleafwaxC31", "d13C"],
  ["d13CleafwaxC31err", "d13C"],
  ["d13CleafwaxC33", "d13C"],
  ["d13CleafwaxC33err", "d13C"],
  ["d13CMean", "d13C"],
  ["d13CPisid", "d13C"],
  ["d13CPrecision", "uncertainty"],
  ["d13CPrecisionComposite", "d13C"],
  ["d13CStandard", "uncertainty"],
  ["d13CStandardComposite", "d13C"],
  ["d13Cwax", "d13C"],
  ["d15N/14N", "d15N"],
  ["d180_corrc", "d18O"],
  ["D18O", "d18O"],
  ["d18O  encrustation", "d18O"],
  ["d18O (Palmyra composite)", "d18O"],
  ["d18O (raw)", "d18O"],
  ["d18O (RT 10)", "d18O"],
  ["d18O (scaled)", "d18O"],
  ["d18O (Sea Level Corrected)", "d18O"],
  ["d18O Avg", "d18O"],
  ["d18O bulk calcite", "d18O"],
  ["d18O carbonate", "d18O"],
  ["d18O carbonate corrected for dolomite", "d18O"],
  ["d18O Chironomid", "d18O"],
  ["d18O error", "uncertainty"],
  ["d18O Lake water", "d18O"],
  ["d18O ostracod", "d18O"],
  ["d18O pore ice", "d18O"],
  ["d18O pore ice sw corr", "d18O"],
  ["d18O VPDB", "d18O"],
  ["d18O_2.5", "uncertaintyLow95"],
  ["d18O_210yr", "d18O"],
  ["d18O_97.5", "uncertaintyHigh95"],
  ["d18o_acicula", "d18O"],
  ["d18O_annual", "d18O"],
  ["d18o_bulloides", "d18O"],
  ["D18O_corrected", "d18O"],
  ["d18o_crassaformis", "d18O"],
  ["d18o_dutertrei", "d18O"],
  ["d18O_error", "uncertainty"],
  ["d18O_Gb", "d18O"],
  ["d18O_Grass_leaf", "d18O"],
  ["d18O_Grass_leaf_error", "uncertainty"],
  ["d18o_inflata", "d18O"],
  ["d18o_mabahethi", "d18O"],
  ["d18o_marginata", "d18O"],
  ["d18o_menardii", "d18O"],
  ["d18o_obliquiloculata", "d18O"],
  ["d18o_pachyderma", "d18O"],
  ["d18o_pachyderma_d", "d18O"],
  ["d18O_PDB", "d18O"],
  ["d18o_peregrina", "d18O"],
  ["d18o_quinqueloba", "d18O"],
  ["d18o_ruber", "d18O"],
  ["d18o_ruber_lato", "d18O"],
  ["d18o_ruber_pink", "d18O"],
  ["d18o_ruber_stricto", "d18O"],
  ["d18o_sacculifer", "d18O"],
  ["d18O_SMOW", "d18O"],
  ["d18O_Sphagnum", "d18O"],
  ["d18O_Sphagnum_error", "uncertainty"],
  ["d18O_sw", "d18O"],
  ["d18O_sw_annual", "d18O"],
  ["d18O_swcorr", "d18O"],
  ["d18o_tumida", "d18O"],
  ["d18O_vp–sp", "d18O"],
  ["d18O_vPDB", "d18O"],
  ["D18O-", "uncertaintyLow"],
  ["D18O+", "uncertaintyHigh"],
  ["d18OBsi", "d18O"],
  ["d18Ocarb", "d18O"],
  ["d18OComposite", "d18O"],
  ["d18Odiatom", "d18O"],
  ["d18Og.rub", "d18O"],
  ["D18OIVC", "d18O"],
  ["D18Oivc-", "uncertaintyLow"],
  ["D18Oivc+", "uncertaintyHigh"],
  ["d18Omean", "d18O"],
  ["d18OPisid", "d18O"],
  ["d18OPrecision", "uncertainty"],
  ["d18OPrecisionComposite", "uncertainty"],
  ["d18OStandard", "uncertainty"],
  ["d18OStandardComposite", "uncertainty"],
  ["d18Osw", "d18O"],
  ["d18Osw-g.rub", "d18O"],
  ["d18Osw-sl-g.rubw", "d18O"],
  ["d18OTerrestrialGastropods", "d18O"],
  ["d18Otr", "d18O"],
  ["d18Otr-", "d18O"],
  ["d18Otr+", "d18O"],
  ["d18OUncertainty", "uncertainty"],
  ["d18OUncertaintyHigh", "uncertaintyHigh"],
  ["d18OUncertaintyLow", "uncertaintyLow"],
  ["d2H avg", "d2H"],
  ["d2H C20", "d2H"],
  ["d2H C20 FAME", "d2H"],
  ["d2H C20 FAME SEM", "d2H"],
  ["d2H C21 alkane", "d2H"],
  ["d2H C21 alkane SEM", "d2H"],
  ["d2H C22", "d2H"],
  ["d2H C22 FAME", "d2H"],
  ["d2H C22 FAME SEM", "d2H"],
  ["d2H C23", "d2H"],
  ["d2H C23 alkane", "d2H"],
  ["d2H C23 alkane SEM", "d2H"],
  ["d2H C24 FAME", "d2H"],
  ["d2H C24 FAME SEM", "d2H"],
  ["d2H C25", "d2H"],
  ["d2H C25 alkane", "d2H"],
  ["d2H C25 alkane SEM", "d2H"],
  ["d2H C25 error", "d2H"],
  ["d2H C25:2", "d2H"],
  ["d2H C26 FAME", "d2H"],
  ["d2H C26 FAME SEM", "d2H"],
  ["d2H C27", "d2H"],
  ["d2H C27 alkane", "d2H"],
  ["d2H C27 alkane SEM", "d2H"],
  ["d2H C27 error", "d2H"],
  ["d2H C28 FAME", "d2H"],
  ["d2H C28 FAME SEM", "d2H"],
  ["d2H C29", "d2H"],
  ["d2H C29 alkane", "d2H"],
  ["d2H C29 alkane SEM", "d2H"],
  ["d2H C29 error", "d2H"],
  ["d2H C30", "d2H"],
  ["d2H C30 FAME", "d2H"],
  ["d2H C30 FAME SEM", "d2H"],
  ["d2H C31", "d2H"],
  ["d2H C31 alkane", "d2H"],
  ["d2H C31 alkane SEM", "d2H"],
  ["d2H C31 error", "d2H"],
  ["d2H C32 FAME", "d2H"],
  ["d2H C32 FAME SEM", "d2H"],
  ["d2H C33 alkane", "d2H"],
  ["d2H C33 alkane SEM", "d2H"],
  ["d2H pore ice", "d2H"],
  ["d2H pore ice sw corr", "d2H"],
  ["d2H precip", "d2H"],
  ["d2H_C16", "d2H"],
  ["d2H_C26", "d2H"],
  ["d2H_C28", "d2H"],
  ["d2H_C30", "d2H"],
  ["d2HC24", "d2H"],
  ["d2HC26", "d2H"],
  ["d2HC28", "d2H"],
  ["d2HC29", "d2H"],
  ["d2HC30", "d2H"],
  ["d2HleafwaxC28", "d2H"],
  ["d2HleafwaxC28err", "uncertainty"],
  ["d2HleafwaxC29", "d2H"],
  ["d2HleafwaxC29err", "d2H"],
  ["d2HleafwaxC31", "d2H"],
  ["d2HleafwaxC31err", "d2H"],
  ["d2HleafwaxC33", "d2H"],
  ["d2HleafwaxC33err", "d2H"],
  ["d2Hsw", "d2H"],
  ["D50", "grainSize"],
  ["DateID", "sampleID"],
  ["DBD", "dryBulkDensity"],
  ["dD", "d2H"],
  ["dD error", "uncertainty"],
  ["dD IV", "d2H"],
  ["dD std dev", "uncertainty1s"],
  ["dD unc", "uncertainty"],
  ["dD_C29", "d2H"],
  ["dD_C30", "d2H"],
  ["dD_C31", "d2H"],
  ["dD_C31_sd", "d2H"],
  ["dD_iceVolCorrected", "d2H"],
  ["dD_IVandbio", "d2H"],
  ["dD_IVonly", "d2H"],
  ["dD_swcorr", "d2H"],
  ["dd18O5pt", "d18O"],
  ["dDC29", "d2H"],
  ["dDC31", "d2H"],
  ["dDP", "d2H"],
  ["dDP_1s_lower", "uncertaintyLow1s"],
  ["dDP_1s_upper", "uncertaintyHigh1s"],
  ["dDUncertainty", "uncertainty"],
  ["dDwax", "d2H"],
  ["dDwax Corrected", "d2H"],
  ["dDwax_corr", "d2H"],
  ["dDwax_iv", "d2H"],
  ["dDwax_IVC", "d2H"],
  ["debrisLayThick", "layerThickness"],
  ["DecQ", "streamflow"],
  ["deep.temp", "temperature"],
  ["deltaT", "deltaTemperature"],
  ["deltaT - 1 sigma", "uncertaintyLow1s"],
  ["deltaT + 1 sigma", "uncertaintyHigh1s"],
  ["Density", "density"],
  ["Depth", "depth"],
  ["Depth blf", "depth"],
  ["depth corrected", "depth"],
  ["depth_bot", "depthBottom"],
  ["depth_bottom", "depthBottom"],
  ["depth_cmbs", "depth"],
  ["depth_core", "depth"],
  ["depth_core1", "depth"],
  ["depth_corr_cm", "depth"],
  ["Depth_eventFree", "depth"],
  ["depth_m", "depth"],
  ["depth_merge", "depth"],
  ["depth_merged", "depth"],
  ["depth_range", "needsToBeSplitIntoMultipleColumns"],
  ["depth_top", "depthTop"],
  ["depth_top_m", "depthTop"],
  ["depth-range", "needsToBeSplitIntoMultipleColumns"],
  ["depth.bottom", "depthBottom"],
  ["depth.composite", "depth"],
  ["depth.lake", "lakeLevel"],
  ["depth.top", "depthTop"],
  ["depthByCore", "depth"],
  ["depthComp", "depth"],
  ["depthComposite", "depth"],
  ["depthice", "depth"],
  ["depthRange", "needsToBeSplitIntoMultipleColumns"],
  ["depthwe", "depth"],
  ["detrendMg", "magnesium"],
  ["deutEx", "deuteriumExcess"],
  ["diatom_abundance", "diatomCount"],
  ["Diatoms_per_traverse", "diatomCount"],
  ["discharge", "streamflow"],
  ["DMAR", "dust"],
  ["DMAR_error", "uncertainty"],
  ["DMAR_uncertainty", "uncertainty"],
  ["dN15", "d15N"],
  ["dN15_corrected", "d15N"],
  ["dolo-wt%", "dolomite"],
  ["DrillHole Depth", "depth"],
  ["Drilling project", "site"],
  ["drive-depth", "depth"],
  ["droughtIndex (PC1)", "PC1"],
  ["Dry Bulk Density", "dryBulkDensity"],
  ["dry sample mass", "sedimentDry"],
  ["dry_bd", "dryBulkDensity"],
  ["DUNE_A", "core"],
  ["dustFlux", "dust"],
  ["dxs", "deuteriumExcess"],
  ["Dysprosium", "dysprosium"],
  ["effectiveMoisture", "effectivePrecipitation"],
  ["ELA", "equilibriumLineAltitude"],
  ["ELA_alt", "equilibriumLineAltitude"],
  ["elevation a.s.l.", "elevation"],
  ["elevation sample", "elevation"],
  ["enddate", "uncertaintyLow"],
  ["enddate_uncertaintyHigh95", "uncertaintyHigh95"],
  ["enddate_uncertaintyLow95", "uncertaintyLow95"],
  ["ENSO_events", "ElNinoEvent"],
  ["entityName", "notes"],
  ["Epsilon C28-C22", "epsilonC28C22"],
  ["Epsilon C28-C22 uncertainty", "uncertainty"],
  ["Epsilon C28-C24", "epsilonC28C24"],
  ["Epsilon C28-C24 uncertainty", "uncertainty"],
  ["Epsilon C29-C23", "epsilonC29C23"],
  ["Epsilon Uncertainty", "uncertainty"],
  ["Epsilon28-22", "epsilonC28C22"],
  ["Epsilon28-22uncertainty", "uncertainty"],
  ["Erbium", "erbium"],
  ["err", "uncertainty"],
  ["error", "uncertainty"],
  ["error_older_age", "uncertaintyHigh"],
  ["error_younger_age", "uncertaintyLow"],
  ["error1", "uncertainty"],
  ["error2", "uncertainty"],
  ["error3", "uncertainty"],
  ["errorLow", "uncertaintyLow"],
  ["errorLow2", "uncertaintyLow"],
  ["errorUp", "uncertaintyHigh"],
  ["errorUp2", "uncertaintyHigh"],
  ["EstDryBD", "dryBulkDensity"],
  ["Eu anomaly", "europium"],
  ["Eu/Zr-z", "Eu/Zr"],
  ["Europium", "europium"],
  ["eventLayerThick", "layerThickness"],
  ["F", "fluorine"],
  ["F_", "fluorine"],
  ["Facies", "facies"],
  ["Fe", "iron"],
  ["Fe peak area", "iron"],
  ["Feb", "temperature"],
  ["FebQ", "streamflow"],
  ["FeCa", "Fe/Ca"],
  ["FeCa_log", "Fe/Ca"],
  ["FeProp", "iron"],
  ["Fld lay thick", "layerThickness"],
  ["Flood lay (annual)", "layerThickness"],
  ["Flood lay (fall)", "layerThickness"],
  ["Flood lay (spring)", "layerThickness"],
  ["Flood lay (summer)", "layerThickness"],
  ["Flood lay (winter)", "layerThickness"],
  ["floodLayThick", "layerThickness"],
  ["floods", "flood"],
  ["flux_dino", "dinocyst"],
  ["Foram", "foraminifera"],
  ["FRA06 Air Temperature", "temperature"],
  ["Friedel-3-ene concentration", "concentration"],
  ["Friedel-3-ene d13C", "d13C"],
  ["Friedel-3-ene d2H", "d2H"],
  ["from_68", "uncertainty1s"],
  ["from_95", "uncertainty2s"],
  ["G. bulloides", "globigerinoidesBulloides"],
  ["G. ruber w δ18O [‰ PDB]", "d18O"],
  ["Gadolium", "gadolinium"],
  ["Gbulloidesd18O", "d18O"],
  ["GDD5", "growing degree days"],
  ["GoE", "circulationIndex"],
  ["GoF", "circulationIndex"],
  ["grain size 125um-2000um", "grainSize"],
  ["Grain size mean", "grainSize"],
  ["GrainSizeMode", "grainSize"],
  ["grayscale20lp_detrended", "grayscale"],
  ["grey_scale", "grayscale"],
  ["GrowthRate", "growthRate"],
  ["Gruber", "globigerinoidesRuber"],
  ["hasAragoniteCorrection", "correction"],
  ["hasAragoniteCorrectionComposite", "correction"],
  ["hasHiatusComposite", "hasHiatus"],
  ["HIndex", "humidificationIndex"],
  ["hobdob", "deleteThisColumn"],
  ["Holmium", "holmium"],
  ["Hop-17(21)-ene concentration", "concentration"],
  ["Hop-17(21)-ene d13C", "d13C"],
  ["Hop-17(21)-ene d2H", "d2H"],
  ["HumidificationIndex", "humidificationIndex"],
  ["hybrid", "composite"],
  ["Hz-ic1", "PC1"],
  ["Hz-ic2", "PC2"],
  ["Hz-ic3", "PC3"],
  ["Hz-ic4", "PC4"],
  ["Hz-ic5", "PC5"],
  ["Hz-ic6", "PC6"],
  ["Ia", "brGDGT-Ia"],
  ["Ib", "brGDGT-Ib"],
  ["Ic", "brGDGT-Ic"],
  ["Ice Accumulation", "accumulation"],
  ["Ice_core_C", "temperature"],
  ["ice_melt_fraction", "iceMelt"],
  ["ID", "sampleID"],
  ["IIa", "brGDGT-IIa5me"],
  ["IIa'", "brGDGT-IIa6me"],
  ["IIb", "brGDGT-IIb5me"],
  ["IIb'", "brGDGT-IIb6me"],
  ["IIc", "brGDGT-IIc5me"],
  ["IIc'", "brGDGT-IIc6me"],
  ["IIIa", "brGDGT-IIIa5me"],
  ["IIIa'", "brGDGT-IIIa6me"],
  ["IIIb", "brGDGT-IIIb5me"],
  ["IIIb'", "brGDGT-IIIb6me"],
  ["IIIc", "brGDGT-IIIc5me"],
  ["IIIc'", "brGDGT-IIIc6me"],
  ["IMON1953", "seaIce"],
  ["IMON1953_i", "uncertaintyLow"],
  ["IMON1953_s", "uncertaintyHigh"],
  ["IMON1953/3", "deleteThisColumn"],
  ["Inc/Coh", "inc/coh"],
  ["Inferred BSi", "BSi"],
  ["IntCal09Age", "age"],
  ["interpolatedTemperature", "temperature"],
  ["interval", "deleteThisColumn"],
  ["IP25_flux", "IP25"],
  ["IRD", "iceRaftedDebris"],
  ["irm", "IRM"],
  ["IRM_softFlux", "IRM"],
  ["Iso adjustment for ocean calibration", "correction"],
  ["ITCZ_index", "ITCZ"],
  ["Jan", "temperature"],
  ["JanQ", "streamflow"],
  ["JAS_error", "uncertainty"],
  ["JAS-", "uncertaintyLow"],
  ["JAS+", "uncertaintyHigh"],
  ["JASerror", "uncertainty"],
  ["JUL", "temperature"],
  ["JulTanom", "temperature"],
  ["JulTanomLoess", "temperature"],
  ["JulyQ", "streamflow"],
  ["JUN", "temperature"],
  ["June-July precipitation", "precipitation"],
  ["JuneQ", "streamflow"],
  ["K", "potassium"],
  ["K peak area", "potassium"],
  ["K_", "potassium"],
  ["K37s", "K37"],
  ["KProp", "potassium"],
  ["kurtosis", "grainSizeKurtosis"],
  ["L", "reflectance"],
  ["La", "lanthanum"],
  ["Lab Code", "sampleID"],
  ["Lab ID", "sampleID"],
  ["label", "sampleID"],
  ["Lake Level", "lakeLevel"],
  ["Lake Level a.s.l.", "lakeLevel"],
  ["lakeAreaError", "uncertainty"],
  ["LakeDepth", "lakeLevel"],
  ["LakeLevel_cm_", "lakeLevel"],
  ["lakeLevelHi", "uncertaintyHigh"],
  ["lakeLevelLo", "uncertaintyLow"],
  ["lakeLevelMax", "uncertaintyHigh"],
  ["lakeLevelMin", "uncertaintyLow"],
  ["lakeLevelRelative", "lakeLevel"],
  ["LakeName", "site"],
  ["lakeStatus", "lakeLevel"],
  ["lakeVolumeError", "uncertainty"],
  ["Lamina_thickness", "layerThickness"],
  ["LaminaThickenss", "layerThickness"],
  ["latewood width", "latewoodWidth"],
  ["latitude sample", "latitude"],
  ["layer", "eventLayer"],
  ["layer_type", "eventLayer"],
  ["LazerProfiler", "deleteThisColumn"],
  ["levelid", "sampleID"],
  ["Lithic Flux", "lithics"],
  ["Lithics", "lithics"],
  ["lithologic unit", "facies"],
  ["lithology", "facies"],
  ["ln(Al/Si)", "Al/Si"],
  ["ln(Fe/Ca)", "Fe/Ca"],
  ["ln(Fe/K)", "Fe/K"],
  ["ln(K/Al)", "K/Al"],
  ["ln(Ti/Ca)", "Ti/Ca"],
  ["log_BaCa", "Ba/Ca"],
  ["log_MgCa", "Mg/Ca"],
  ["log_SrCa", "Sr/Ca"],
  ["log(Fe/Ca)", "Fe/Ca"],
  ["log(Ti/Ca)", "Ti/Ca"],
  ["logdepthtop", "depthTop"],
  ["logdepthtop-EDC99", "depthTop"],
  ["logdepttop", "depthTop"],
  ["logSalinity", "salinity"],
  ["LOI550", "LOI"],
  ["LOI950", "LOI"],
  ["Long chain n-acid avg d2H", "d2H"],
  ["Long Chain n-alkane avg d2H", "d2H"],
  ["longitude sample", "longitude"],
  ["lower95", "uncertaintyLow95"],
  ["lowerErr", "uncertaintyLow"],
  ["lowerErr2", "uncertaintyLow95"],
  ["Lutetium", "lutetium"],
  ["M-flood", "flood"],
  ["M-flood 200 yr avg", "flood"],
  ["M-flood 30 yr sum", "flood"],
  ["MAAT", "temperature"],
  ["Magnetic Susceptibility", "MS"],
  ["MAP", "precipitation"],
  ["MAP_max", "uncertaintyHigh"],
  ["MAP_min", "uncertaintyLow"],
  ["MAP1-sigma", "uncertainty1s"],
  ["MAP2-sigma", "uncertainty2s"],
  ["MarchQ", "streamflow"],
  ["Marine09", "age"],
  ["mass dry", "sedimentDry"],
  ["mass dry >1mm", "sedimentDry"],
  ["mass dry 106 to 1000 um", "sedimentDry"],
  ["mass dry 63 to 106 um", "sedimentDry"],
  ["massacum", "MAR"],
  ["massDry", "sedimentDry"],
  ["massDry_1mm", "sedimentDry"],
  ["MassMagSus", "MS"],
  ["MAT", "temperature"],
  ["MAT_max", "uncertaintyHigh"],
  ["MAT_min", "uncertaintyLow"],
  ["Material", "material"],
  ["MATmax", "uncertaintyHigh"],
  ["MATmin", "uncertaintyLow"],
  ["max age", "uncertaintyHigh"],
  ["max RH", "uncertaintyHigh"],
  ["max_age_95", "uncertaintyHigh95"],
  ["maxAge", "uncertaintyHigh"],
  ["maxAge95", "uncertaintyHigh95"],
  ["MaxElevM", "uncertaintyHigh"],
  ["MAY", "temperature"],
  ["MayQ", "streamflow"],
  ["MBT'", "MBT"],
  ["MBT'5Me", "MBT"],
  ["MBTsd", "uncertainty1s"],
  ["mean depth", "depth"],
  ["Mean Sedim rate", "sedimentationRate"],
  ["meanAge_kaBP", "age"],
  ["MeanT", "temperature"],
  ["Median cal age", "age"],
  ["medianAge", "age"],
  ["medianAge_kaBP", "age"],
  ["melt", "iceMelt"],
  ["meltLayerFrequency", "iceMelt"],
  ["meltLayers", "iceMelt"],
  ["meltUncertaintyHigh", "uncertaintyHigh"],
  ["meltUncertaintyLow", "uncertaintyLow"],
  ["MethaneIndex", "methaneIndex"],
  ["Mg", "magnesium"],
  ["Mg__", "magnesium"],
  ["Mg_Ca", "Mg/Ca"],
  ["Mg_Ca_sd", "uncertainty1s"],
  ["Mg/Ca Raw", "Mg/Ca"],
  ["MgCa", "Mg/Ca"],
  ["mgca_bulloides", "Mg/Ca"],
  ["mgca_crassaformis", "Mg/Ca"],
  ["mgca_dutertrei", "Mg/Ca"],
  ["mgca_inflata", "Mg/Ca"],
  ["mgca_obliquiloculata", "Mg/Ca"],
  ["mgca_pachyderma", "Mg/Ca"],
  ["mgca_pachyderma_d", "Mg/Ca"],
  ["mgca_ruber", "Mg/Ca"],
  ["mgca_ruber_lato", "Mg/Ca"],
  ["mgca_ruber_pink", "Mg/Ca"],
  ["mgca_ruber_stricto", "Mg/Ca"],
  ["mgca_sacculifer", "Mg/Ca"],
  ["mgca_truncatulinoides", "Mg/Ca"],
  ["MgDetrended", "magnesium"],
  ["Mid-chain n-acid avg d2H", "d2H"],
  ["Midchain n-alkane avg d2H", "d2H"],
  ["MidpointDepth", "depth"],
  ["min age", "uncertaintyLow"],
  ["min RH", "uncertaintyLow"],
  ["minAge", "uncertaintyLow"],
  ["minAge95", "uncertaintyLow95"],
  ["MinElevM", "uncertaintyLow"],
  ["mineral_flux", "mineralogy"],
  ["mineralogyComposite", "mineralogy"],
  ["Mn", "manganese"],
  ["MnFe", "Mn/Fe"],
  ["MnTi", "Mn/Ti"],
  ["Mo", "molybdenum"],
  ["Mo MAR (ug/cm2/ky)", "MAR"],
  ["Mo_xs", "molybdenum"],
  ["Moisture_index", "effectivePrecipitation"],
  ["molarCN", "C/N"],
  ["MSAT", "temperature"],
  ["MSAT Russell 2018", "temperature"],
  ["N", "nitrogen"],
  ["n C24", "C24n-alkanoicAcid"],
  ["n C26", "C26n-alkanoicAcid"],
  ["n C28", "C28n-alkanoicAcid"],
  ["n-C28", "C28n-alkanoicAcid"],
  ["Na", "sodium"],
  ["Na_", "sodium"],
  ["NC", "N/C"],
  ["nC24", "C24n-alkanoicAcid"],
  ["nC26", "C26n-alkanoicAcid"],
  ["nC28", "C28n-alkanoicAcid"],
  ["nC28_dD", "d2H"],
  ["nC28_err", "C28n-alkanoicAcid"],
  ["nC28_rep", "C28n-alkanoicAcid"],
  ["nC30_dD", "d2H"],
  ["nC30_err", "uncertainty"],
  ["nC30_rep", "C30n-alkanoicAcid"],
  ["Nd", "neodymium"],
  ["Ndutertreid18O", "d18O"],
  ["NdutertreiMg/Ca", "Mg/Ca"],
  ["NH4_", "ammonium"],
  ["Ni", "nickel"],
  ["NO3", "nitrate"],
  ["NO3_", "nitrate"],
  ["noID", "deleteThisColumn"],
  ["nonReliabled18O", "d18O"],
  ["nonReliabletemperature", "temperature"],
  ["nonReliableTemperature 1", "temperature"],
  ["nonReliabletemperature 2", "temperature"],
  ["nonReliableTemperature_1", "temperature"],
  ["nonReliableTemperature_2", "temperature"],
  ["nonReliableTemperature_3", "temperature"],
  ["nonReliableTemperature_4", "temperature"],
  ["Norg", "organicNitrogen"],
  ["norm Si/Ti", "Si/Ti"],
  ["norm Silicon", "silicon"],
  ["Norm33", "n-alkaneRatio"],
  ["note", "notes"],
  ["notes_C5", "notes"],
  ["NOV", "temperature"],
  ["NovQ", "streamflow"],
  ["num_samples", "sampleCount"],
  ["Numbe_counted", "count"],
  ["number", "count"],
  ["Number of TR samples", "sampleCount"],
  ["Number_counted", "count"],
  ["numInZone", "count"],
  ["OC-MAR (g)", "organicCarbon"],
  ["OC-MAR (mg)", "organicCarbon"],
  ["OCT", "temperature"],
  ["OctQ", "streamflow"],
  ["oktas_r", "cloudiness"],
  ["OM", "organicMatter"],
  ["OM dens", "organicMatter"],
  ["OpenVegetation___", "landscapeCover"],
  ["organic", "organicMatter"],
  ["Organic carbon concentration", "organicCarbon"],
  ["originalCoreDepth", "depth"],
  ["originalCoreName", "core"],
  ["OriginalSampleID", "sampleID"],
  ["P", "precipitation"],
  ["P-flood", "flood"],
  ["P-flood 200 yr avg", "flood"],
  ["P-flood 30 yr sum", "flood"],
  ["p-SD", "uncertaintyLow1s"],
  ["p+SD", "uncertaintyHigh1s"],
  ["P1", "PC1"],
  ["Pannom", "precipitation"],
  ["PannomMax", "uncertaintyHigh"],
  ["PannomMaxUncertainty", "uncertaintyHigh"],
  ["PannomMin", "uncertaintyLow"],
  ["PannomMinUncertainty", "uncertaintyLow"],
  ["Panom", "precipitation"],
  ["PanomMax", "uncertaintyHigh"],
  ["PanomMaxUncertainty", "uncertaintyHigh"],
  ["PanomMin", "uncertaintyLow"],
  ["PanomMinUncertainty", "uncertaintyLow"],
  ["Pb", "lead"],
  ["PC1gs", "PC1"],
  ["PCA1", "PC1"],
  ["PCA2", "PC2"],
  ["pcpanomCI5", "uncertaintyLow95"],
  ["pcpanomCI95", "uncertaintyHigh90"],
  ["pdsi", "PDSI"],
  ["Peat", "peat"],
  ["peatFlux", "peat"],
  ["pHsoil", "pH"],
  ["Picea/Artemesia", "Picea/Artemisia"],
  ["planktic.d13C", "d13C"],
  ["planktic.d18O", "d18O"],
  ["planktic.MgCa", "Mg/Ca"],
  ["planktonic.d13C", "d13C"],
  ["planktonic.d13C.error", "uncertainty"],
  ["planktonic.d18O", "d18O"],
  ["planktonic.d18O.error", "uncertainty"],
  ["planktonic.foram.abundance", "foraminifera"],
  ["planktonic.MgCa", "Mg/Ca"],
  ["planktonic.MgCa.error", "uncertainty"],
  ["plotName", "sampleID"],
  ["PLS_C2_temp", "temperature"],
  ["PLS-1", "index"],
  ["PLS-2", "index"],
  ["Pmax", "uncertaintyHigh"],
  ["Pmin", "uncertaintyLow"],
  ["Pollen Sequence", "sequence"],
  ["Pollen_T", "temperature"],
  ["ppm As", "arsenic"],
  ["ppm Ba", "barium"],
  ["ppm Be", "beryllium"],
  ["ppm Cd", "cadmium"],
  ["ppm Cd/% Mn", "Cd/Mn"],
  ["ppm Co", "cobalt"],
  ["ppm Cr", "chromium"],
  ["ppm Cu", "copper"],
  ["ppm La", "lanthanum"],
  ["ppm Mn", "manganese"],
  ["ppm Mo", "molybdenum"],
  ["ppm Ni", "nickel"],
  ["ppm Pb", "lead"],
  ["ppm Sc", "scandium"],
  ["ppm Sr", "strontium"],
  ["ppm V", "vanadium"],
  ["ppm Y", "yttrium"],
  ["ppm Zn", "zinc"],
  ["ppm Zr", "zirconium"],
  ["ppmBa/%Al", "Ba/Al"],
  ["Praseodymium", "praseodymium"],
  ["Precip", "precipitation"],
  ["Precip d2H", "d2H"],
  ["Precip dD 10 CI", "d2HUncertaintyLow80"],
  ["Precip dD 25 CI", "uncertaintyLow95"],
  ["Precip dD 75 CI", "uncertaintyHigh50"],
  ["Precip dD 90 CI", "d2HUncertaintyHigh80"],
  ["precip_1s_lower", "uncertaintyLow1s"],
  ["precip_1s_upper", "uncertaintyHigh1s"],
  ["precip_1s_uppper", "uncertaintyHigh1s"],
  ["precip-", "uncertaintyLow"],
  ["precip+", "uncertaintyHigh"],
  ["precip51yr", "precipitation"],
  ["precip5yr", "precipitation"],
  ["Precipitation", "precipitation"],
  ["precipitation (Febr-July)", "precipitation"],
  ["precipitation (May-Jume)", "precipitation"],
  ["precipitation (May-June)", "precipitation"],
  ["precipitation (with H-set)", "precipitation"],
  ["precipitation std", "uncertainty1s"],
  ["precipitation std (with H-set)", "uncertainty1s"],
  ["precipitation with 20-year Spline", "precipitation"],
  ["precipitationUncertainty", "uncertainty"],
  ["precipobs", "precipitation"],
  ["Q0.025", "uncertaintyLow95"],
  ["Q0.025, ice volume adjusted", "uncertaintyLow95"],
  ["Q0.025, ice volume and vegetation adjusted", "uncertaintyLow95"],
  ["Q0.16", "uncertaintyLow1s"],
  ["Q0.16, ice volume adjusted", "uncertaintyLow1s"],
  ["Q0.16, ice volume and vegetation adjusted", "uncertaintyLow1s"],
  ["Q0.84", "uncertaintyHigh1s"],
  ["Q0.84, ice volume adjusted", "uncertaintyHigh1s"],
  ["Q0.84, ice volume and vegetation adjusted", "uncertaintyHigh1s"],
  ["Q0.975", "uncertaintyHigh95"],
  ["Q0.975, ice volume adjusted", "uncertaintyHigh95"],
  ["Q0.975, ice volume and vegetation adjusted", "uncertaintyHigh95"],
  ["R570_630", "R570/R630"],
  ["R650_700", "R650/R700"],
  ["R660_670", "RABD660670"],
  ["RABD660_670", "RABD660670"],
  ["RABD660;670 index", "RABD660670"],
  ["radiocarbonDatesAD0x2FBC", "age14C"],
  ["range", "uncertainty"],
  ["Rb", "rubidium"],
  ["Rb peak area", "rubidium"],
  ["Rb/Sr", "Rb87/Sr86"],
  ["RBar", "RBAR"],
  ["RCS.ars", "deleteThisColumn"],
  ["Recon0x2EDate", "year"],
  ["red_color_intensity_units", "reflectance"],
  ["redness", "reflectance"],
  ["Region", "site"],
  ["ReliabIeYN1", "isReliable"],
  ["ReliabIeYN2", "isReliable"],
  ["reliable", "isReliable"],
  ["reliable 1", "isReliable"],
  ["reliable 2", "isReliable"],
  ["reliable_1", "isReliable"],
  ["reliable_2", "isReliable"],
  ["reliable_3", "isReliable"],
  ["reliable_4", "isReliable"],
  ["Reliable?", "isReliable"],
  ["repeats", "notes"],
  ["residual", "residualChronology"],
  ["Reworked", "notes"],
  ["RH", "relativeHumidity"],
  ["Ring Width Index", "trsgi"],
  ["ruberD18", "d18O"],
  ["S", "sulfur"],
  ["sambleID", "sampleID"],
  ["Samp thick", "thickness"],
  ["Samp vol", "volume"],
  ["Sample", "sampleID"],
  ["sample # in section", "sampleID"],
  ["Sample ID", "sampleID"],
  ["Sample interval", "sampleID"],
  ["Sample label", "sampleID"],
  ["Sample thickness", "thickness"],
  ["sample_code", "sampleID"],
  ["sample_number", "sampleID"],
  ["sample_thickness", "thickness"],
  ["sampleDensity", "sampleCount"],
  ["sampleIDa", "sampleID"],
  ["sampleIDb", "sampleID"],
  ["sampleIDc", "sampleID"],
  ["sampleNumber", "sampleID"],
  ["samples", "sampleID"],
  ["Sand", "sand"],
  ["SAUG", "salinity"],
  ["SAUG_i", "uncertaintyLow"],
  ["SAUG_s", "uncertaintyHigh"],
  ["SAUG/3", "deleteThisColumn"],
  ["SBT", "temperature"],
  ["Sc", "scandium"],
  ["scPDSI", "PDSI"],
  ["scPDSI (Febr-June)", "PDSI"],
  ["SD", "uncertainty1s"],
  ["SD_anomaly", "uncertainty1s"],
  ["SE", "uncertainty1s"],
  ["sea ice concentration, winter", "seaIce"],
  ["Sea_Ice_conc", "seaIce"],
  ["Sea_Ice_months", "seaIce"],
  ["seaIceCoverDuration", "seaIce"],
  ["seaIceDiatoms", "diatomCount"],
  ["Sec label", "section"],
  ["Section", "section"],
  ["Section [#]", "section"],
  ["Section #", "section"],
  ["Section depth", "depth"],
  ["Section depth bottom", "depthBottom"],
  ["Section depth top", "depthTop"],
  ["section name", "section"],
  ["Section number", "section"],
  ["sed rate", "sedimentationRate"],
  ["Sedim rate", "sedimentationRate"],
  ["sedimentWeight", "sedimentDry"],
  ["sedRate", "sedimentationRate"],
  ["segment", "segmentLength"],
  ["SEP", "temperature"],
  ["SeptQ", "streamflow"],
  ["Series Number", "sampleID"],
  ["SETE", "salinity"],
  ["SETE_i", "uncertaintyLow"],
  ["SETE_s", "uncertaintyHigh"],
  ["SETE/3", "deleteThisColumn"],
  ["SFEV", "salinity"],
  ["SFEV_i", "uncertaintyLow"],
  ["SFEV_s", "uncertaintyHigh"],
  ["SFEV/3", "deleteThisColumn"],
  ["SHCal04Age", "age"],
  ["SHIV", "salinity"],
  ["SHIV_i", "uncertaintyLow"],
  ["SHIV_s", "uncertaintyHigh"],
  ["SHIV/3", "deleteThisColumn"],
  ["SI", "MS"],
  ["Si peak area", "silicon"],
  ["Silt", "silt"],
  ["SiProp", "silicon"],
  ["sisalSampleID", "sampleID"],
  ["sisalSampleIDComposite", "sampleID"],
  ["Site", "site"],
  ["site/hole", "site"],
  ["siteName", "site"],
  ["skewness", "grainSizeSkewness"],
  ["Slide count", "count"],
  ["SM/IlliteChlorite", "index"],
  ["smapleID", "sampleID"],
  ["smoothedTemp", "temperature"],
  ["SO4__", "SO4"],
  ["soilPH", "pH"],
  ["soilTemp", "temperature"],
  ["sorting", "grainSizeSorting"],
  ["Sr", "strontium"],
  ["Sr (ppm)", "strontium"],
  ["Sr peak area", "strontium"],
  ["Sr_Ca", "Sr/Ca"],
  ["SrCa", "Sr/Ca"],
  ["SrCa_annual", "Sr/Ca"],
  ["SrCaUncertainty", "uncertainty"],
  ["sss", "salinity"],
  ["SST", "temperature"],
  ["SST_amj", "temperature"],
  ["SST_from_planktic0x2Ed18O", "temperature"],
  ["SST_from_planktic0x2EMgCa", "temperature"],
  ["SST_from_Uk37", "temperature"],
  ["SST_LDI", "temperature"],
  ["SST-d18O", "temperature"],
  ["sstEnsemble", "temperature"],
  ["Stal.ID", "core"],
  ["startdate", "uncertaintyHigh"],
  ["startdate_uncertaintyHigh95", "uncertaintyHigh95"],
  ["startdate_uncertaintyLow95", "uncertaintyLow95"],
  ["std", "uncertainty1s"],
  ["stdDev", "uncertainty1s"],
  ["stdDev___", "uncertainty1s"],
  ["stdev C24", "uncertainty1s"],
  ["stdev C26", "uncertainty1s"],
  ["stdev C28", "uncertainty1s"],
  ["StDev C28 dD", "uncertainty1s"],
  ["stdev weighted average", "uncertainty1s"],
  ["stdevC24", "uncertainty1s"],
  ["stdevC25", "uncertainty1s"],
  ["stdevC26", "uncertainty1s"],
  ["stdevC27", "uncertainty1s"],
  ["stdevC28", "uncertainty1s"],
  ["stdevC29", "uncertainty1s"],
  ["stdevC31", "uncertainty1s"],
  ["subT", "temperature"],
  ["Sulfur", "sulfur"],
  ["Sulphur", "sulfur"],
  ["SumDiatoms", "diatom"],
  ["Summer precipitation", "precipitation"],
  ["Summer Precipitation Error", "uncertainty"],
  ["sumUK37", "Uk37"],
  ["SunFrac", "solarIrradiance"],
  ["SunFracMax", "uncertaintyHigh"],
  ["SunFracMin", "uncertaintyLow"],
  ["surface.temp", "temperature"],
  ["surface.temp.error", "uncertainty"],
  ["surface.temp.hi", "uncertaintyHigh"],
  ["surface.temp.lo", "uncertaintyLow"],
  ["T anomaly", "temperature"],
  ["T_site_std", "uncertainty"],
  ["T-SD", "uncertaintyLow1s"],
  ["t-source", "temperature"],
  ["T.MinusSD", "uncertaintyLow1s"],
  ["T.PlusSD", "uncertaintyHigh1s"],
  ["T+SD", "uncertaintyHigh1s"],
  ["Tanom", "temperature"],
  ["Taraxer-14-ene d13C", "d13C"],
  ["Taraxer-14-ene d2H", "d2H"],
  ["TC", "totalCarbon"],
  ["temp", "temperature"],
  ["Temp Anom 10 CI", "temperature"],
  ["Temp Anom 25", "temperature"],
  ["Temp Anom 75", "temperature"],
  ["Temp Anom 90", "temperature"],
  ["Temp Anom Best", "temperature"],
  ["Temp Anom FOR15", "temperature"],
  ["Temp Anom FRA06", "temperature"],
  ["Temp Anom FRA06-TR", "temperature"],
  ["temp2", "temperature"],
  ["temp2s", "temperature"],
  ["tempAv0", "temperature"],
  ["tempAv8", "temperature"],
  ["Temperature", "temperature"],
  ["temperature 1", "temperature"],
  ["Temperature 1 sigma range high", "uncertaintyHigh1s"],
  ["Temperature 1 sigma range low", "uncertaintyLow1s"],
  ["temperature 2", "temperature"],
  ["temperature_1", "temperature"],
  ["temperature_2", "temperature"],
  ["temperature_3", "temperature"],
  ["temperature_4", "temperature"],
  ["temperature_error", "uncertainty"],
  ["temperatureCold", "uncertaintyLow"],
  ["temperatureComposite", "temperature"],
  ["temperaturer2", "temperature"],
  ["temperatureUncertainty", "uncertainty"],
  ["temperatureWarm", "uncertaintyHigh"],
  ["tempError", "uncertainty"],
  ["tempErrorLower", "uncertaintyLow"],
  ["tempErrorPlus", "uncertaintyHigh"],
  ["tempErrorUpper", "uncertaintyHigh"],
  ["tempK", "temperature"],
  ["tempNoElevCorrection", "temperature"],
  ["tempNoSourceCorrection", "temperature"],
  ["tempPartialCorrect", "temperature"],
  ["tempSmooth5", "temperature"],
  ["Terbium", "terbium"],
  ["TETE", "temperature"],
  ["TETE_i", "uncertaintyLow"],
  ["TETE_s", "uncertaintyHigh"],
  ["TETE/3", "deleteThisColumn"],
  ["tex86l", "TEX86"],
  ["TFEV", "temperature"],
  ["TFEV_i", "uncertaintyLow"],
  ["TFEV_s", "uncertaintyHigh"],
  ["TFEV/3", "deleteThisColumn"],
  ["Thickness", "thickness"],
  ["thicknessComposite", "thickness"],
  ["THIV", "temperature"],
  ["THIV_i", "uncertaintyLow"],
  ["THIV_s", "uncertaintyHigh"],
  ["THIV/3", "deleteThisColumn"],
  ["Thulium", "thulium"],
  ["Ti", "titanium"],
  ["Ti peak area", "titanium"],
  ["Ti/Ca", "Ca/Ti"],
  ["Tiash", "titanium"],
  ["TiProp", "titanium"],
  ["Titanium", "titanium"],
  ["TN", "totalNitrogen"],
  ["to_68", "uncertainty1s"],
  ["to_95", "uncertainty2s"],
  ["TOC", "organicCarbon"],
  ["TOC_flux", "organicCarbon"],
  ["TOCmg", "organicCarbon"],
  ["top", "depthTop"],
  ["Top Depth", "depthTop"],
  ["top depth in section", "depthTop"],
  ["Top_depth", "depthTop"],
  ["topDepth", "depthTop"],
  ["total", "count"],
  ["Total Organic Carbon", "organicCarbon"],
  ["Total_grains_counted", "count"],
  ["total_non_Chaetoceros_counted", "count"],
  ["total_xount", "count"],
  ["TotalAmmoniaBeccarii", "count"],
  ["totalC37", "C37Alkenone"],
  ["TotalPollen", "totalPollen"],
  ["Tree rin width", "ringWidth"],
  ["Tree ring", "trsgi"],
  ["Tree ring Index", "trsgi"],
  ["Tree ring width index", "trsgi"],
  ["Tree ring with", "ringWidth"],
  ["Tree-ring index", "trsgi"],
  ["Tree-ring width", "ringWidth"],
  ["TreeCover", "treeCover"],
  ["TreeCover_max", "uncertaintyHigh"],
  ["TreeCover_min", "uncertaintyLow"],
  ["TreePollen", "totalPollen"],
  ["TRW", "ringWidth"],
  ["Tsource", "temperature"],
  ["TTerror", "uncertainty"],
  ["U", "uranium"],
  ["U371sigmaUncertainty-", "uncertainty1s"],
  ["UK_error", "uncertainty"],
  ["UK'37", "Uk37'"],
  ["UK37", "Uk37"],
  ["UK37_error", "uncertainty"],
  ["UK37-SFS Values", "Uk37"],
  ["uncertainty_1", "uncertainty"],
  ["uncertainty_2", "uncertainty"],
  ["uncertainty_3", "uncertainty"],
  ["uncertainty_4", "uncertainty"],
  ["uncertainty_plus", "uncertaintyHigh"],
  ["uncertainty_temperature", "uncertainty"],
  ["uncertainty.temperature", "uncertainty"],
  ["UncertaintyDust0x5B0x250x5D0x28Minus0x29", "uncertaintyLow"],
  ["UncertaintyDust0x5B0x250x5D0x28Plus0x29", "uncertaintyHigh"],
  ["uncorrected_depth_bot", "depthBottom"],
  ["uncorrected_depth_top", "depthTop"],
  ["undertainty_minus", "uncertaintyLow"],
  ["UnkownColumn", "deleteThisColumn"],
  ["upper band", "uncertaintyHigh"],
  ["upper95", "uncertaintyHigh95"],
  ["upperErr", "uncertaintyHigh"],
  ["upperErr2", "uncertaintyHigh"],
  ["V", "vanadium"],
  ["Varve thickness", "varveThickness"],
  ["Varve_number", "count"],
  ["Varve_width", "varveThickness"],
  ["varveCountedAgeAD0x2FBC", "age"],
  ["varveCountedAgeKa", "age"],
  ["Water Table", "waterTableDepth"],
  ["Water Table Detrended", "waterTableDepth"],
  ["water wm", "waterTableDepth"],
  ["water_table_depth", "waterTableDepth"],
  ["Water_tableDepth", "waterTableDepth"],
  ["waterBalance", "effectivePrecipitation"],
  ["WetBD", "wetBulkDensity"],
  ["Winter Precipitation", "precipitation"],
  ["Winter Precipitation error", "uncertainty"],
  ["WMT_max", "uncertaintyHigh"],
  ["WMT_min", "uncertaintyLow"],
  ["WMT1-sigma", "uncertainty1s"],
  ["WMT2-sigma", "uncertainty2s"],
  ["WMTmax", "uncertaintyHigh"],
  ["WMTmin", "uncertaintyLow"],
  ["WoodyCover___", "percent"],
  ["WR11_d18O", "d18O"],
  ["WR11_SrCa", "Sr/Ca"],
  ["x_C", "carbon"],
  ["x_Clay", "clay"],
  ["X_radiograph_dark_layer", "reflectance"],
  ["x_Sand", "sand"],
  ["x_Silt", "silt"],
  ["x18O", "d18O"],
  ["x18ORub_", "d18O"],
  ["Y", "yttrium"],
  ["Year", "year"],
  ["Year (CE)", "year"],
  ["Year b2k", "year"],
  ["year start", "year"],
  ["year_old", "uncertaintyHigh"],
  ["yearBottom", "uncertaintyLow"],
  ["yearEnsemble", "year"],
  ["yearRounded", "year"],
  ["Years", "year"],
  ["Years BP", "year"],
  ["Years for ocean correction", "correction"],
  ["yearsPerSample", "duration"],
  ["yearTop", "uncertaintyLow"],
  ["Ytterbium", "ytterbium"],
  ["Z_score", "zscore"],
  ["Zn", "zinc"],
  ["Zr", "zirconium"],
  ["δ13C n-alkanes", "d13C"],
  ["δ13C n-alkanes std dev", "d13C"],
  ["δ18O", "d18O"],
  ["δDaq", "d2H"],
  ["δDterr", "d2H"],
  ["ΔδDterr-aq", "Dd2H"],
]
